---
- hosts: webservers
  tasks:
  - name: Loome allalaadmiseks kataloogi
    file:
      path=/root/allalaadimised
      owner=root
      group=root
      mode=0755
      state=directory

  - name: Laeme alla mysql_5.7 repo paketi apt-i lisamiseks
    get_url:
      url: http://repo.mysql.com/mysql-apt-config_0.8.24-1_all.deb
      dest: "/root/allalaadimised"
      mode: 0440

  - name: Installeerime mysql repo
    apt: "deb=/root/allalaadimised/mysql-apt-config_0.8.24-1_all.deb"

  - name: Installeerime mysql
    apt: name=mysql-server update_cache=yes state=present

  - name: installeerime python-msqldb
    apt: name=python-mysqldb update_cache=yes state=latest

  - name: Loome root login faili
    copy:
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: 0600
      content: |
          [client]
          user=root
          password=qwerty

  - name: Loome kasutaja
    mysql_user:
      name: root
      password: qwerty
      priv: '*.*:ALL,GRANT'
      state: present

  - name: restart mysql
    service: name=mysql state=restarted

