---
- hosts: webservers
  tasks:
  - name: installing MySQL server on server
    apt: pkg={{item}} update_cache=yes cache_valid_time=86400 state=present
    with_items:
    - python-mysqldb
    - mysql-server





  - name: Start mysql service
    service: name=mysql state=started





  - name: configuring root user pass and priveliges
    mysql_user: name=root host=phpmyadmin password=Juut1337 priv=*.*:ALL,GRANT
    with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
    
    
  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true$




  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='$





  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='Juut$





  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='Juut13$





  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value=$




  - name: installid
    command: apt install php php-cgi php-mysqli php-pear php-mbstring php-gette$
